# Generated by Django 5.0.1 on 2024-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_alter_userinfo_account_alter_userinfo_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrettyNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(max_length=11, verbose_name="Phone Number"),
                ),
                ("price", models.IntegerField(verbose_name="Price")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                            (5, "Level 5"),
                        ],
                        default=1,
                        verbose_name="Level",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Occupied"), (2, "Not occupied")],
                        default=2,
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
    ]
