# Generated by Django 5.0.1 on 2024-01-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "levels",
                    models.SmallIntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low")],
                        default=1,
                        verbose_name="Level",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="Title")),
                ("detail", models.TextField(verbose_name="Detail")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.admin",
                        verbose_name="PersonIC",
                    ),
                ),
            ],
        ),
    ]
