# Generated by Django 5.0.1 on 2024-01-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0005_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.admin",
                verbose_name="Person in charge",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="Order ID")),
                ("title", models.CharField(max_length=64, verbose_name="Title")),
                ("price", models.IntegerField(verbose_name="Price")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Not yet paid"), (2, "Already paid")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.admin",
                        verbose_name="Administrator",
                    ),
                ),
            ],
        ),
    ]
